### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Trictonicmp** [marilirulita/Ruby_Capstone#22]
[Repo Project](https://github.com/marilirulita/Ruby_Capstone/projects/1)

#### There's 4 people in this team:
- @LuisSalas94  [Team Member 1]
- @marilirulita [Team Member 2]
- @joshuaivie [Team Member 3]
- @Trictonicmp [Team Member 4]

**Comment by prolajumokeoni** [comment]
Hi @Team,
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Project is setup correctly



## Required Changes ♻️
Please ensure all requirements from the list for a given student in the [project requirements ](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) have a corresponding card in the Kanban board, currently some cards are missing based on the project requirements 👍🏿 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Trictonicmp** [comment]
Hi, @prolajumokeoni Thank you for the feedback!
I would like to know if we need to create a project card for each list item of the project requirements. 
We made the cards thinking of tasks to be made, for example, creating a class includes, creating the file, setting the class properties/methods, and tests for each method of the class, database tables are another tasks because it's out o the scope of creating a class and so on. We think this would be a good approach but if we are requested to make every list item one card, we would do so.
I'm currently taking a look at the project requirements to see if we have some items missing.

Thank you in advance for your time.

[Edit]
We decided to separate the tasks into smaller tasks, now should be correct, asking for another review.

**Comment by uwadonat** [comment]
## Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
